name: Build Docker Image
#this build stage should only be kicked off once the testing workflow is green(not implemented)
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v3


          - name: Build and push Docker image
            uses: docker/build-push-action@v4
            with:
              context: .
            