name: Testing Workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run tests in the test directory
              run: |
                cd test
                echo "Running tests in the test directory..."
                pytest
            